version: '2'
services:
  dankmeme:
    build: .
    container_name: dankmeme
    image: dankmeme:latest
    volumes:
      - ./memes.txt:/opt/app/memes.txt
    environment:
      - 'DISCORD_KEY=${DISCORD_KEY}'
